helmfile/create/all:
	@echo " "
	@echo "Syncing all Kubernetes resources using helmfiles..."
	@helmfile sync || echo "Services couldn't be synced."
	@echo "Helmfile deployment finished."
	@echo " "
	@echo " "
