# Credit: https://github.com/robotpy/robotpy-docs/blob/master/gensidebar.py
# This file generates the sidebar/toctree for all RobotPy projects and should
# be copied to each project when it is updated
#

import os


def write_sidebar(fname, contents):
    with open(fname, "w") as fp:
        fp.write(contents)


def generate_sidebar(conf, conf_api):

    # determine 'latest' or 'stable'
    # if not conf.do_gen:
    do_gen = os.environ.get("SIDEBAR", None) == "1" or conf["on_rtd"]
    version = conf["rtd_version"]

    lines = ["", ".. DO NOT MODIFY! THIS PAGE IS AUTOGENERATED!", ""]

    def toctree(name):
        lines.extend(
            [".. toctree::", "    :caption: %s" % name, "    :maxdepth: 1", "    :hidden:", ""]
        )

    def endl():
        lines.append("")

    def write(desc, link):
        if conf_api == "deepcell-kiosk":
            args = desc, link
        elif not do_gen:
            return
        else:
            args = (
                desc,
                "https://deepcell-kiosk.readthedocs.io/en/%s/%s.html" % (version, link),
            )

        lines.append("    %s <%s>" % args)

    def write_subproject(desc, project, link, subsection=None):
        if project != conf_api:
            if subsection != None:
                subsection = '#'+subsection
            else:
                subsection = ''

            if do_gen:
                lines.append(
                    '    {desc} <https://deepcell-kiosk.readthedocs.io/projects/{project}/en/{version}/{link}.html{subsection}>'.format(
                        desc=desc,
                        project=project,
                        version=version,
                        link=link,
                        subsection=subsection
                    )
                )
        else:
            lines.append('    {desc} <index>'.format(desc=desc))

    #
    # Specify the sidebar contents here
    #

    toctree('Deepcell Kiosk')
    # write('Home', 'index')
    write('Getting Started', 'GETTING_STARTED')
    write('Troubleshooting', 'TROUBLESHOOTING')
    write('Tutorial: Custom Jobs', 'CUSTOM-JOB')
    write('Developer Documentation', 'DEVELOPER')
    endl()

    toctree('Kiosk Redis Consumer')
    write_subproject('API', 'kiosk-redis-consumer', 'API')
    endl()

    print(lines)

    write_sidebar("_sidebar.rst.inc", "\n".join(lines))
