#!/usr/bin/env bash

AWS_ACCESS_KEY_ID=$1
AWS_SECRET_ACCESS_KEY=$2
AWS_S3_BUCKET=$3
NAMESPACE=$4
AWS_MIN_GPU_NODES=$5
AWS_MAX_GPU_NODES=$6

# create some derivative GPU-related variables for use in autoscaling
export GPU_MAX_TIMES_TWO=$(($AWS_MAX_GPU_NODES*2))
export GPU_MAX_TIMES_THREE=$(($AWS_MAX_GPU_NODES*3))
export GPU_MAX_TIMES_FOUR=$(($AWS_MAX_GPU_NODES*4))
export GPU_MAX_TIMES_FIVE=$(($AWS_MAX_GPU_NODES*5))
export GPU_MAX_TIMES_TEN=$(($AWS_MAX_GPU_NODES*10))
export GPU_MAX_TIMES_TWENTY=$(($AWS_MAX_GPU_NODES*20))
export GPU_MAX_TIMES_THIRTY=$(($AWS_MAX_GPU_NODES*30))
export GPU_MAX_TIMES_FOURTY=$(($AWS_MAX_GPU_NODES*40))
export GPU_MAX_TIMES_FIFTY=$(($AWS_MAX_GPU_NODES*50))
export GPU_MAX_TIMES_SEVENTY_FIVE=$(($AWS_MAX_GPU_NODES*75))
export GPU_MAX_TIMES_ONE_HUNDRED=$(($AWS_MAX_GPU_NODES*100))
export GPU_MAX_TIMES_TWO_HUNDRED=$(($AWS_MAX_GPU_NODES*200))
export GPU_MAX_DIVIDED_BY_TWO=$(($AWS_MAX_GPU_NODES/2))
export GPU_MAX_DIVIDED_BY_THREE=$(($AWS_MAX_GPU_NODES/3))
export GPU_MAX_DIVIDED_BY_FOUR=$(($AWS_MAX_GPU_NODES/4))
export GPU_NODE_MAX_SIZE=${AWS_MAX_GPU_NODES}

export KOPS_CLUSTER_NAME=${NAMESPACE}.k8s.local
export KOPS_DNS_ZONE=${NAMESPACE}.k8s.local
export KOPS_STATE_STORE=s3://${NAMESPACE}
export CLOUD_PROVIDER=aws

make create_cache_path
printenv | grep -e CLOUD_PROVIDER > ${CACHE_PATH}/env
printenv | grep -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_S3_BUCKET -e NAMESPACE \
  -e AWS_MIN_GPU_NODES \
  -e AWS_MAX_GPU_NODES \
  -e GPU_MAX_TIMES_TWO \
  -e GPU_MAX_TIMES_THREE \
  -e GPU_MAX_TIMES_FOUR \
  -e GPU_MAX_TIMES_FIVE \
  -e GPU_MAX_TIMES_TEN \
  -e GPU_MAX_TIMES_TWENTY \
  -e GPU_MAX_TIMES_THIRTY \
    -e GPU_MAX_TIMES_FOURTY \
    -e GPU_MAX_TIMES_FIFTY \
    -e GPU_MAX_TIMES_SEVENTY_FIVE \
    -e GPU_MAX_TIMES_ONE_HUNDRED \
    -e GPU_MAX_TIMES_TWO_HUNDRED \
  -e GPU_MAX_DIVIDED_BY_TWO \
  -e GPU_MAX_DIVIDED_BY_THREE \
  -e GPU_MAX_DIVIDED_BY_FOUR \
    -E GPU_NODE_MAX_SIZE > ${CACHE_PATH}/env.aws
# tailcmd "Create Cluster" "---COMPLETE---" make create
# export CLUSTER_ADDRESS=$(sed -E 's/^export CLUSTER_ADDRESS=(.+)$/\1/' ./cluster_address)

echo "hi"
