repositories:
  # Add the Jetstack Helm repository
  - name: jetstack
    url: https://charts.jetstack.io
  # Kubernetes incubator repo of helm charts
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:

################################################################################
## Certificate Manager #########################################################
################################################################################

#
# References:
#   - https://github.com/cloudposse/charts/blob/master/incubator/nginx-ingress/values.yaml
#
- name: cert-manager
  namespace: cert-manager
  labels:
    chart: cert-manager
    repo: jetstack
    component: cert-manager
    namespace: cert-manager
    vendor: kubernetes
  chart: jetstack/cert-manager
  version: v1.8.2
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  hooks:
  - events: ["postsync"]
    # Give cert-manager time to initialize itself
    showlogs: true
    command: /bin/sleep
    args:
      - 15
  values:
    - installCRDs: true

      # serviceAccount:
      #   annotations:
      #     iam.gke.io/gcp-service-account: {{ env "GCP_SERVICE_ACCOUNT" | default "cloud-dns-sa-not-found"}}

      ingressShim:
        # Use "letsencrypt-prod" for production.
        defaultIssuerName: {{ env "CERTIFICATE_MANAGER_CLUSTER_ISSUER" | default "letsecrypt-staging" }}
        defaultIssuerKind: ClusterIssuer
        defaultIssuerGroup: cert-manager.io

################################################################################
## Certificate Issuers #########################################################
################################################################################

#
# Certificate Issuers
- name: cert-manager-issuers
  needs:
    - cert-manager/cert-manager
  namespace: cert-manager
  chart: incubator/raw
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  disableValidation: true
  values:
    - resources:

      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-staging
        spec:
          acme:
            server: https://acme-staging-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: letsencrypt-staging
            solvers:
            - selector: {}
              dns01:
                cloudDNS:
                  project: {{ env "CLOUDSDK_CORE_PROJECT" | default "project-not-found" }}
                  serviceAccountSecretRef:
                    name: clouddns-dns01-solver-svc-acct
                    key: key.json

      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-prod
        spec:
          acme:
            server: https://acme-v02.api.letsencrypt.org/directory
            privateKeySecretRef:
              name: letsencrypt-prod
            solvers:
            - selector: {}
              dns01:
                cloudDNS:
                  project: {{ env "CLOUDSDK_CORE_PROJECT" | default "project-not-found" }}
                  serviceAccountSecretRef:
                    name: clouddns-dns01-solver-svc-acct
                    key: key.json
