repositories:
  - name: bitnami-pre-2022
    url: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami

releases:

################################################################################
## Redis Data Store ############################################################
################################################################################

#
# References:
#   - https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
#
- name: redis
  labels:
    chart: redis
    component: database
  chart: bitnami/redis
  version: 16.13.0
  namespace: deepcell
  wait: true
  atomic: true
  timeout: 600
  cleanupOnFail: true
  values:
    - architecture: replication

      auth:
        enabled: false
        sentinel: false

      commonConfiguration: |-
        # Enable AOF https://redis.io/topics/persistence#append-only-file
        appendonly yes
        # Disable RDB persistence, AOF persistence already enabled.
        save ""
        # Prevent fsync() from being called in the main process while a
        # BGSAVE or BGREWRITEAOF is in progress.
        # If you have latency problems turn this to "yes". Otherwise leave it as
        # "no" that is the safest pick from the point of view of durability.
        no-appendfsync-on-rewrite yes

      master:
        resources:
          requests:
            cpu: 200m
            memory: 256Mi

      replica:
        replicaCount: 3
        resources:
          requests:
            cpu: 200m
            memory: 256Mi

      sentinel:
        enabled: true

      sysctl:
        mountHostSys: true
        command:
          - /bin/sh
          - -c
          - |-
            install_packages systemd procps
            sysctl -w net.core.somaxconn=10000
            echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
