releases:

################################################################################
## Bucket-Monitor ##############################################################
################################################################################

#
# References:
#   - https://github.com/vanvalenlab/kiosk-console/blob/master/conf/charts/bucket-monitor/values.yaml
#
- name: bucket-monitor
  namespace: deepcell
  labels:
    chart: bucket-monitor
    component: bucket-monitor
    namespace: deepcell
    vendor: vanvalenlab
    default: true
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/bucket-monitor'
  version: 0.2.0
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  values:
    - replicas: 1

      image:
        repository: vanvalenlab/kiosk-bucket-monitor
        tag: 0.5.0

      resources:
        requests:
          cpu: 500m
          memory: 256Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi

      env:
        AGE_THRESHOLD: "259200"
        PREFIX: "uploads/,output/"
        INTERVAL: "21600"
        REDIS_HOST: "redis"
        REDIS_PORT: "26379"
{{ if eq (env "CLOUD_PROVIDER" | default "aws") "aws" }}
        STORAGE_BUCKET: 's3://{{ env "BUCKET" | default "broken_default" }}'
{{ else }}
        STORAGE_BUCKET: 'gs://{{ env "CLOUDSDK_BUCKET" | default "broken_default" }}'
{{ end }}
