releases:

################################################################################
## AutoScaler ################################################################
################################################################################

#
# References:
#   - https://github.com/vanvalenlab/kiosk-console/blob/master/conf/charts/autoscaler/values.yaml
#
- name: autoscaler
  namespace: deepcell
  labels:
    chart: autoscaler
    component: autoscaler
    namespace: deepcell
    vendor: vanvalenlab
    default: true
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/autoscaler'
  version: 0.1.0
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  values:
    - replicas: 1

      image:
        repository: vanvalenlab/kiosk-autoscaler
        tag: 0.6.0

      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi

      env:
        QUEUES: "mesmer,segmentation,tracking"
        QUEUE_DELIMITER: ","
        RESOURCE_NAME: "tf-serving"
        RESOURCE_TYPE: "deployment"
        RESOURCE_NAMESPACE: "deepcell"
        DEBUG: "true"
        INTERVAL: 5
        REDIS_HOST: "redis"
        REDIS_PORT: 26379
        REDIS_INTERVAL: 1
        # These should not change
        MAX_PODS: 1
        MIN_PODS: '{{ env "GPU_NODE_MIN_SIZE" | default 0 }}'
        KEYS_PER_POD: 1
