releases:

################################################################################
## Redis Janitor ###############################################################
################################################################################

#
# References:
#   - https://github.com/vanvalenlab/kiosk-console/blob/master/conf/charts/redis-janitor/values.yaml
#
- name: redis-janitor
  namespace: deepcell
  labels:
    chart: redis-janitor
    component: redis-janitor
    namespace: deepcell
    vendor: vanvalenlab
    default: true
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/redis-janitor'
  version: 0.1.0
  wait: true
  timeout: 300
  atomic: true
  cleanupOnFail: true
  values:
    - replicas: 1

      image:
        repository: vanvalenlab/kiosk-redis-janitor
        tag: 0.6.0

      resources:
        requests:
          cpu: 400m
          memory: 128Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi

      env:
        QUEUES: "mesmer,segmentation,caliban"
        DEBUG: "true"
        INTERVAL: "5"
        REDIS_HOST: "redis"
        REDIS_PORT: "26379"
