helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Redis-Janitor ###############################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "redis-janitor"
  namespace: "deepcell"
  labels:
    chart: "redis-janitor"
    component: "redis-janitor"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/redis-janitor'
  version: "0.1.0"
  values:
    - replicas: 1

      image:
        repository: "vanvalenlab/kiosk-redis-janitor"
        tag: "0.1"
        pullPolicy: "Always"

      serviceAccount:
        # Specifies whether a ServiceAccount should be created
        create: true
        # The name of the ServiceAccount to use.
        # If not set and create is true, a name is generated using the fullname template
        name:

      resources:
        requests:
          cpu: 300m
          memory: 128Mi
        # limits:
        #   cpu: 100m
        #   memory: 64Mi

      env:
        DEBUG: "true"
        INTERVAL: "5"
        REDIS_HOST: "redis-master"
        REDIS_PORT: "6379"
