helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Data-Processing #############################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "data-processing"
  namespace: "deepcell"
  labels:
    chart: "data-processing"
    component: "deepcell"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/data-processing'
  version: "0.1.0"
  values:
    - replicas: 1

      image:
        repository: "vanvalenlab/kiosk-data-processing"
        tag: "0.1"
        pullPolicy: "Always"

      service:
        type: "ClusterIP"

        httpIngressEnabled: true
        internalHttpPort: 8080
        httpTargetPort: 8080
        externalHttpPort: 8080

        httpsIngressEnabled: false
        internalHttpsPort: 8443
        httpsTargetPort: 8443
        externalHttpsPort: 8443

        prometheusEnabled: true
        prometheusHttpPort: 8000

        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8000"
          prometheus.io/scrape: "true"

      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"

      resources:
        requests:
          cpu: 1500m
          memory: 1536Mi
        # limits:
        #   cpu: 100m
        #   memory: 2048Mi

      env:
        LISTEN_PORT: 8080
        PROMETHEUS_PORT: 8000
        PROMETHEUS_ENABLED: true
