helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## AutoScaler ################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: "benchmarking"
  namespace: "deepcell"
  labels:
    chart: "benchmarking"
    component: "benchmarking"
    namespace: "deepcell"
    vendor: "vanvalenlab"
    default: "true"
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/benchmarking'
  version: "0.1.0"
  values:
    - app_name: "benchmarking"
      deployment_name: "benchmarking-deployment"
      replicas: 1
      image_name: "vanvalenlab/kiosk-benchmarking"
      image_version: "multiple_zip_files"
      container_name: "benchmarking-container"
      service_account_name: "benchmarking-service-account"
      env:
        REDIS_HOST: "redis-master"
        REDIS_PORT: "6379"
        BENCHMARKING_PU_TYPE_AND_NUMBER: '{{ env "BENCHMARKING_PU_TYPE_AND_NUMBER" | default "NA" }}'
        BENCHMARKING_PU_TYPE: '{{ env "BENCHMARKING_PU_TYPE" | default "NA" }}'
        IMG_NUM: '{{ env "IMG_NUM" | default "0" }}'
        BENCHMARK_MODEL: '{{ env "BENCHMARK_MODEL" | default "NA" }}'
        BENCHMARK_MODEL_VERSION: '{{ env "BENCHMARK_MODEL_VERSION" | default "NA" }}'
        BENCHMARK_POSTPROCESSING: '{{ env "BENCHMARK_POSTPROCESSING" | default "NA" }}'
        BENCHMARK_CUTS: '{{ env "BENCHMARK_CUTS" | default "NA" }}'
        GPU_TYPE: '{{ env "GPU_TYPE" | default "NA" }}'
        CLUSTER_ADDRESS: '{{ env "CLUSTER_ADDRESS" | default "NA" }}'
        UPLOAD_METHOD: '{{ env "UPLOAD_METHOD" | default "direct" }}'
        IMAGES_PER_ZIP: '{{ env "IMAGES_PER_ZIP" | default "100" }}'
{{ if eq (env "CLOUD_PROVIDER" | default "gke") "gke" }}
        BUCKET: '{{ env "GKE_BUCKET" | default "invalid-bucket" }}'
{{ else }}
        BUCKET: '{{ env "AWS_BUCKET" | default "invalid-bucket" }}'
{{ end }}
        BUCKET_FOLDER: '{{ env "BUCKET_UPLOAD_FOLDER" | default "uploads" }}'
