repositories:
  # Stable repo of official helm charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:

################################################################################
## Prometheus Adapter                                                         ##
## exports data for the cutom metrics API                                     ##
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/prometheus-adapter
#   - https://github.com/DirectXMan12/k8s-prometheus-adapter
#
- name: prometheus-adapter
  namespace: monitoring
  labels:
    chart: prometheus-adapter
    repo: prometheus-community
    component: monitoring
    namespace: monitoring
    vendor: coreos
    default: true
  chart: prometheus-community/prometheus-adapter
  version: 2.17.1
  wait: true
  timeout: 600
  atomic: true
  cleanupOnFail: true
  values:
    - logLevel: 4

      metricsRelistInterval: 1m

      # Url to access prometheus
      prometheus:
        url: http://prometheus-operator-prometheus
        port: 9090

      replicas: 1

      resources: {}
        # requests:
        #   cpu: 100m
        #   memory: 128Mi
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
